import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './global.css';
import Header from "@/inc/components/header/Header";
import Footer from "@/inc/components/footer/Footer";
import QueryProvider from "@/providers/QueryProvider";
import { dehydrate, HydrationBoundary, QueryClient } from "@tanstack/react-query";
import { getGenres, getMovies } from "@/features/services/getMovie_service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CINE AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery({ queryKey: ['movies'], queryFn: getMovies }),
    queryClient.prefetchQuery({ queryKey: ['genres'], queryFn: getGenres }),
  ]);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <HydrationBoundary state={dehydrate(queryClient)} >
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </HydrationBoundary>
        </QueryProvider>
      </body>
    </html>
  );
}
